// <auto-generated />
using System;
using CinemaProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaProject.DAL.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20220217170631_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaProject.DAL.Entities.CinemaPlace", b =>
                {
                    b.Property<int>("Id_CinemaPlace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cinemaPlace")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR(8)")
                        .HasColumnName("number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("street");

                    b.Property<int>("ZipCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("zipCode");

                    b.HasKey("Id_CinemaPlace");

                    b.ToTable("CinemaPlaces");

                    b.HasData(
                        new
                        {
                            Id_CinemaPlace = 1,
                            City = "Charleroi",
                            Name = "Roosevelt",
                            Number = "3Bis",
                            Street = "Rue Jean Mermoz",
                            ZipCode = 6000
                        },
                        new
                        {
                            Id_CinemaPlace = 2,
                            City = "Liège",
                            Name = "Le Spectaculaire",
                            Number = "24",
                            Street = "Avenue des cerisiers",
                            ZipCode = 4000
                        },
                        new
                        {
                            Id_CinemaPlace = 3,
                            City = "Namur",
                            Name = "Le Parc",
                            Street = "Place des Lumières",
                            ZipCode = 5000
                        });
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.CinemaRoom", b =>
                {
                    b.Property<int>("Id_CinemaRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cinemaRoom")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Can3D")
                        .HasColumnType("BIT")
                        .HasColumnName("can3D");

                    b.Property<bool>("Can4DX")
                        .HasColumnType("BIT")
                        .HasColumnName("can4DX");

                    b.Property<int>("Id_CinemaPlace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cinemaPlace");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("screenHeight");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("screenWidth");

                    b.Property<int>("SitsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sitsCount");

                    b.HasKey("Id_CinemaRoom");

                    b.HasIndex("Id_CinemaPlace");

                    b.ToTable("CinemaRooms");

                    b.HasData(
                        new
                        {
                            Id_CinemaRoom = 1,
                            Can3D = true,
                            Can4DX = false,
                            Id_CinemaPlace = 1,
                            Number = 1,
                            ScreenHeight = 580,
                            ScreenWidth = 1362,
                            SitsCount = 206
                        },
                        new
                        {
                            Id_CinemaRoom = 2,
                            Can3D = true,
                            Can4DX = false,
                            Id_CinemaPlace = 1,
                            Number = 2,
                            ScreenHeight = 580,
                            ScreenWidth = 1362,
                            SitsCount = 206
                        },
                        new
                        {
                            Id_CinemaRoom = 3,
                            Can3D = true,
                            Can4DX = false,
                            Id_CinemaPlace = 2,
                            Number = 1,
                            ScreenHeight = 580,
                            ScreenWidth = 1362,
                            SitsCount = 206
                        },
                        new
                        {
                            Id_CinemaRoom = 4,
                            Can3D = true,
                            Can4DX = false,
                            Id_CinemaPlace = 2,
                            Number = 2,
                            ScreenHeight = 580,
                            ScreenWidth = 1362,
                            SitsCount = 206
                        },
                        new
                        {
                            Id_CinemaRoom = 5,
                            Can3D = true,
                            Can4DX = false,
                            Id_CinemaPlace = 2,
                            Number = 3,
                            ScreenHeight = 580,
                            ScreenWidth = 1362,
                            SitsCount = 206
                        },
                        new
                        {
                            Id_CinemaRoom = 6,
                            Can3D = true,
                            Can4DX = false,
                            Id_CinemaPlace = 3,
                            Number = 1,
                            ScreenHeight = 580,
                            ScreenWidth = 1362,
                            SitsCount = 206
                        },
                        new
                        {
                            Id_CinemaRoom = 7,
                            Can3D = true,
                            Can4DX = true,
                            Id_CinemaPlace = 1,
                            Number = 1,
                            ScreenHeight = 835,
                            ScreenWidth = 1932,
                            SitsCount = 327
                        },
                        new
                        {
                            Id_CinemaRoom = 8,
                            Can3D = false,
                            Can4DX = false,
                            Id_CinemaPlace = 1,
                            Number = 4,
                            ScreenHeight = 1021,
                            ScreenWidth = 2400,
                            SitsCount = 629
                        },
                        new
                        {
                            Id_CinemaRoom = 9,
                            Can3D = false,
                            Can4DX = false,
                            Id_CinemaPlace = 3,
                            Number = 2,
                            ScreenHeight = 1021,
                            ScreenWidth = 2400,
                            SitsCount = 629
                        },
                        new
                        {
                            Id_CinemaRoom = 10,
                            Can3D = false,
                            Can4DX = false,
                            Id_CinemaPlace = 3,
                            Number = 3,
                            ScreenHeight = 1021,
                            ScreenWidth = 2400,
                            SitsCount = 629
                        });
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.Diffusion", b =>
                {
                    b.Property<int>("Id_Diffusion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_diffusion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AudLang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("audLang");

                    b.Property<DateTime>("DiffusionDate")
                        .HasColumnType("DATE")
                        .HasColumnName("diffusionDate");

                    b.Property<TimeSpan>("DiffusionTime")
                        .HasColumnType("TIME")
                        .HasColumnName("diffusionTime");

                    b.Property<int>("Id_CinemaRoom")
                        .HasColumnType("INT")
                        .HasColumnName("id_cinemaRoom");

                    b.Property<int>("Id_Movie")
                        .HasColumnType("INT")
                        .HasColumnName("id_movie");

                    b.Property<int?>("SubTitleLang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subTitleLang");

                    b.HasKey("Id_Diffusion");

                    b.HasIndex("Id_CinemaRoom");

                    b.HasIndex("Id_Movie");

                    b.ToTable("Diffusions");

                    b.HasData(
                        new
                        {
                            Id_Diffusion = 1,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 45, 0, 0),
                            Id_CinemaRoom = 1,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 2,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 30, 0, 0),
                            Id_CinemaRoom = 7,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 3,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 15, 50, 0, 0),
                            Id_CinemaRoom = 1,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 4,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 16, 5, 0, 0),
                            Id_CinemaRoom = 7,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 5,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 17, 30, 0, 0),
                            Id_CinemaRoom = 8,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 6,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 15, 0, 0),
                            Id_CinemaRoom = 6,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 7,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 15, 50, 0, 0),
                            Id_CinemaRoom = 6,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 8,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 17, 30, 0, 0),
                            Id_CinemaRoom = 9,
                            Id_Movie = 4
                        },
                        new
                        {
                            Id_Diffusion = 9,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 30, 0, 0),
                            Id_CinemaRoom = 8,
                            Id_Movie = 1
                        },
                        new
                        {
                            Id_Diffusion = 10,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 17, 0, 0, 0),
                            Id_CinemaRoom = 8,
                            Id_Movie = 1
                        },
                        new
                        {
                            Id_Diffusion = 11,
                            AudLang = 0,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 20, 0, 0, 0),
                            Id_CinemaRoom = 8,
                            Id_Movie = 1,
                            SubTitleLang = 1
                        },
                        new
                        {
                            Id_Diffusion = 12,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 30, 0, 0),
                            Id_CinemaRoom = 3,
                            Id_Movie = 1
                        },
                        new
                        {
                            Id_Diffusion = 13,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 17, 0, 0, 0),
                            Id_CinemaRoom = 3,
                            Id_Movie = 1
                        },
                        new
                        {
                            Id_Diffusion = 14,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 20, 0, 0, 0),
                            Id_CinemaRoom = 3,
                            Id_Movie = 1
                        },
                        new
                        {
                            Id_Diffusion = 15,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 18, 15, 0, 0),
                            Id_CinemaRoom = 2,
                            Id_Movie = 2
                        },
                        new
                        {
                            Id_Diffusion = 16,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 21, 15, 0, 0),
                            Id_CinemaRoom = 2,
                            Id_Movie = 2
                        },
                        new
                        {
                            Id_Diffusion = 17,
                            AudLang = 0,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 14, 0, 0, 0),
                            Id_CinemaRoom = 9,
                            Id_Movie = 2,
                            SubTitleLang = 1
                        },
                        new
                        {
                            Id_Diffusion = 18,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 16, 0, 0, 0),
                            Id_CinemaRoom = 6,
                            Id_Movie = 2
                        },
                        new
                        {
                            Id_Diffusion = 19,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 20, 0, 0, 0),
                            Id_CinemaRoom = 9,
                            Id_Movie = 2
                        },
                        new
                        {
                            Id_Diffusion = 30,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 15, 0, 0),
                            Id_CinemaRoom = 4,
                            Id_Movie = 3
                        },
                        new
                        {
                            Id_Diffusion = 20,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 15, 30, 0, 0),
                            Id_CinemaRoom = 4,
                            Id_Movie = 3
                        },
                        new
                        {
                            Id_Diffusion = 21,
                            AudLang = 0,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 18, 0, 0, 0),
                            Id_CinemaRoom = 4,
                            Id_Movie = 3,
                            SubTitleLang = 1
                        },
                        new
                        {
                            Id_Diffusion = 22,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 13, 15, 0, 0),
                            Id_CinemaRoom = 6,
                            Id_Movie = 3
                        },
                        new
                        {
                            Id_Diffusion = 23,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 16, 30, 0, 0),
                            Id_CinemaRoom = 10,
                            Id_Movie = 3
                        },
                        new
                        {
                            Id_Diffusion = 24,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 18, 15, 0, 0),
                            Id_CinemaRoom = 10,
                            Id_Movie = 3
                        },
                        new
                        {
                            Id_Diffusion = 25,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 14, 15, 0, 0),
                            Id_CinemaRoom = 8,
                            Id_Movie = 5
                        },
                        new
                        {
                            Id_Diffusion = 26,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 16, 45, 0, 0),
                            Id_CinemaRoom = 8,
                            Id_Movie = 5
                        },
                        new
                        {
                            Id_Diffusion = 27,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 14, 15, 0, 0),
                            Id_CinemaRoom = 5,
                            Id_Movie = 5
                        },
                        new
                        {
                            Id_Diffusion = 28,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 16, 45, 0, 0),
                            Id_CinemaRoom = 5,
                            Id_Movie = 5
                        },
                        new
                        {
                            Id_Diffusion = 29,
                            AudLang = 1,
                            DiffusionDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiffusionTime = new TimeSpan(0, 18, 15, 0, 0),
                            Id_CinemaRoom = 5,
                            Id_Movie = 5
                        });
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.Movie", b =>
                {
                    b.Property<int>("Id_Movie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_movie")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("posterUrl");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("releaseYear");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("subTitle");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR(4000)")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("title");

                    b.HasKey("Id_Movie");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id_Movie = 1,
                            Duration = 109,
                            PosterUrl = "encanto.jpg",
                            ReleaseYear = 2021,
                            SubTitle = "La fantastique famille Madrigal",
                            Synopsis = "Synopsis : Dans un mystérieux endroit niché au cœur des montagnes de Colombie, la fantastique famille Madrigal habite une maison enchantée dans une cité pleine de vie, un endroit merveilleux appelé Encanto. L’Encanto a doté chacun des enfants de la famille d’une faculté magique allant d’une force surhumaine au pouvoir de guérison.",
                            Title = "Encanto"
                        },
                        new
                        {
                            Id_Movie = 2,
                            Duration = 114,
                            PosterUrl = "scream.jpg",
                            ReleaseYear = 2022,
                            Synopsis = "Interdit aux moins de 16 ans Vingt-cinq ans après que la paisible ville de Woodsboro a été frappée par une série de meurtres violents, un nouveau tueur revêt le masque de Ghostface et prend pour cible un groupe d'adolescents. Il est déterminé à faire ressurgir les sombres secrets du passé.",
                            Title = "Scream"
                        },
                        new
                        {
                            Id_Movie = 3,
                            Duration = 116,
                            PosterUrl = "uncharted.jpg",
                            ReleaseYear = 2022,
                            Synopsis = "Uncharted est un film américain réalisé par Ruben Fleischer et dont la sortie est prévue en 2022. Il s'agit d'une adaptation cinématographique de la série de jeux vidéo Uncharted développés par Naughty Dog et édités par Sony Interactive Entertainment.",
                            Title = "Uncharted"
                        },
                        new
                        {
                            Id_Movie = 4,
                            Duration = 148,
                            PosterUrl = "spiderman.jpg",
                            ReleaseYear = 2021,
                            SubTitle = "No way home",
                            Synopsis = "Pour la première fois dans son histoire cinématographique, Spider-Man, le héros sympa du quartier est démasqué et ne peut désormais plus séparer sa vie normale de ses lourdes responsabilités de super-héros. Quand il demande de l'aide à Doctor Strange, les enjeux deviennent encore plus dangereux, le forçant à découvrir ce qu'être Spider-Man signifie véritablement.",
                            Title = "Spider-Man"
                        },
                        new
                        {
                            Id_Movie = 5,
                            Duration = 112,
                            PosterUrl = "scene.jpg",
                            ReleaseYear = 2021,
                            Synopsis = "Tous en scène 2 ou Chantez ! 2 au Québec ( Sing 2) est un film d'animation réalisé par Garth Jennings et sorti en 2021. C'est la suite de Tous en scène sorti en 2016 . Buster Moon et ses amis essaient de convaincre la star du rock recluse Clay Calloway de rejoindre leur show d'ouverture .",
                            Title = "Tous en scène 2"
                        });
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.CinemaRoom", b =>
                {
                    b.HasOne("CinemaProject.DAL.Entities.CinemaPlace", "CinemaPlace")
                        .WithMany("CinemaRooms")
                        .HasForeignKey("Id_CinemaPlace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaPlace");
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.Diffusion", b =>
                {
                    b.HasOne("CinemaProject.DAL.Entities.CinemaRoom", "CinemaRoom")
                        .WithMany()
                        .HasForeignKey("Id_CinemaRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.DAL.Entities.Movie", "Movie")
                        .WithMany("Diffusions")
                        .HasForeignKey("Id_Movie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaRoom");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.CinemaPlace", b =>
                {
                    b.Navigation("CinemaRooms");
                });

            modelBuilder.Entity("CinemaProject.DAL.Entities.Movie", b =>
                {
                    b.Navigation("Diffusions");
                });
#pragma warning restore 612, 618
        }
    }
}
